### ISSUE TITLE
Clock app isn't linked.

### ISSUE THREAD

**Issue by fleeting** [tingbot/ocean#1]
The clock app currently isn't linked and looks like the [repo](https://github.com/tingbot-apps/clock) is empty for it. Should it be removed from the ocean until the app is ready?

**Comment by joerick** [comment]
Thanks James, I've uploaded a super minimal clock app from the documentation [tutorial](http://tingbot-python.readthedocs.org/en/latest/gettingstarted.html#your-first-app-a-digital-clock).
