### ISSUE TITLE
How do you install an app from Ocean to a Tingbot?

### ISSUE THREAD

**Issue by BJClark** [tingbot/ocean#11]
I am happy to open a PR to add more documentation for this, but I legitimately can't figure it out! How does one install an app from Ocean to the Tingbot?

**Comment by joerick** [comment]
Hey @BJClark! Download the zip file, uncompress, open with Tide, choose your Tingbot and press upload.

Docs would be great - we could put a page on docs.tingbot.com and link it from the sidebar 👍
